# Generated by Django 4.0 on 2023-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('when', models.DateTimeField()),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
    ]
