# Generated by Django 4.0 on 2023-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
