# Generated by Django 4.0 on 2023-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='when',
            field=models.DateTimeField(null=True),
        ),
    ]
