# Generated by Django 4.2.5 on 2023-09-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='when',
        ),
        migrations.AddField(
            model_name='session',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='saved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
