# Generated by Django 4.2.5 on 2023-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_session_when_session_last_edit_session_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
