# Generated by Django 4.2.5 on 2023-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tag_session_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
