# Generated by Django 4.2.5 on 2023-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_session_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='saved',
            field=models.DateTimeField(),
        ),
    ]
